# Generated by Django 5.2.4 on 2025-07-06 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('DAM', 'Day Ahead Market'), ('RTM', 'Real Time Market')], max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('interval', models.PositiveIntegerField()),
                ('purchase_bid', models.FloatField()),
                ('sell_bid', models.FloatField()),
                ('mcp', models.FloatField()),
                ('mcv', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electricity.product')),
            ],
            options={
                'ordering': ['date', 'interval'],
                'unique_together': {('product', 'date', 'interval')},
            },
        ),
    ]
